
# SEO settings
title: "Sunbo's"
title2: "Blog" # default: ""
description: "A Space to share my experience in coding and life"
keywords: ""
url: http://ex44559.github.io/ # site url
#baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

#google_analytics: UA-XXXXX-XX
repo: http://github.com/ex44559/ex44559.github.io
disqus_shortname: "ex44559"
#twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "sunbo"
  job      : "A post-graduate in HUST."
  bio      : "Go for it."
  thumb    : /images/author.jpg
  email    : sunbo.90s@gmail.com
  url      : http://ex44559.github.io
  github   : http://github.com/ex44559
  #twitter  : http://twitter.com/HeiswayiNrird
  #facebook : https://www.facebook.com/profile.php?id=1257583160
  #linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
